### ISSUE TITLE
Great queue works well!

### ISSUE THREAD

**Issue by andersc** [Deaod/spsc_queue#2]
Hi,

Just wanted to share my work in this domain.

https://github.com/andersc/fastqueue2

Your queue is really awesome!  Great work..

**Comment by Deaod** [comment]
Cool stuff.

spsc_queue will automatically switch to using bit masking for the next index calculation if you give it a power of 2 as size.
spsc_queue probably uses 7 as default for align_log2 for the same reason FastQueue2 is using it for its data.
FastQueue2 seems to use only about 1/16 of the memory it reserves.

Now, it seems like there is no actual issue here, so ill close this.
